name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Build and Test
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test

      - name: Read package.json
        uses: krstphrrr/package-json-version-reader@v1
        id: package-version

      - uses: docker/setup-buildx-action@v3.7.1
        name: Docker Setup Buildx

      - uses: docker/login-action@v3.3.0
        name: Docker Login
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: docker build -t ${{ secrets.DOCKERHUB_LOGIN }}/delay-api:${{ steps.package-version.outputs.version }} .
      - run: docker image push ${{ secrets.DOCKERHUB_LOGIN }}/delay-api:${{ steps.package-version.outputs.version }}